### ISSUE TITLE
Test screen

### ISSUE THREAD

**Issue by tormodAase** [equinor/attenuation-app#16]
- Should contain progress indicator at the top.
- Should contain exit button.
- Should contain testplan renderer

**Comment by dansvend** [comment]
@KaterynaBasik This ready for testing 🧪 

Build number: `2024.0709.49`

**Comment by KaterynaBasik** [comment]
Tested ( build n 2024.0709.49)

- [x] All test screens contain progress indicator at the top. However
     - [ ] #45 
     - [ ] #46
- [x] All text screens contain exit button
- [ ]  All text screens contain testplan renderer

**Comment by dansvend** [comment]
@KaterynaBasik The progress bar should now update as expected and is ready to be testen in build with build number: `2024.712.62`

**Comment by KaterynaBasik** [comment]
> @KaterynaBasik The progress bar should now update as expected and is ready to be tested in build with build number: `2024.712.62`

Tested.
The progress bar now updates as expected.

While testing the volume buttons I noticed this:
when slowly reducing the volume step-by-step till when I no longer hear the sound after the last press. Then I expect to restore the sound by pressing the (+) button once.  But it takes two presses/two steps instead of one for the sound to become audiable again. I can notice this only using noise-cancelling headphones.

**Comment by dansvend** [comment]
> > @KaterynaBasik The progress bar should now update as expected and is ready to be tested in build with build number: `2024.712.62`
> 
> Tested. The progress bar now updates as expected.
> 
> While testing the volume buttons I noticed this: when slowly reducing the volume step-by-step till when I no longer hear the sound after the last press. Then I expect to restore the sound by pressing the (+) button once. But it takes two presses/two steps instead of one for the sound to become audiable again. I can notice this only using noise-cancelling headphones.

Thanks for testing 🙏 I created a new issue on this: #52
